### ISSUE TITLE
Songs suddenly overlap and then the program breaks.

### ISSUE THREAD

**Issue by adriantoto** [HACKER097/wisdom-tree#29]
I installed it with PIP. The first time running, it works fine. After that, the music is overlap and I got this error everytime the tree grow:

Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python310\Scripts\wisdom-tree-script.py", line 33, in <module>
    sys.exit(load_entry_point('wisdom-tree==0.1.4', 'console_scripts', 'wisdom-tree')())
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\wisdom_tree\main.py", line 1030, in run_app
    main()
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\wisdom_tree\main.py", line 883, in main
    addtext(int(maxx / 2), int(maxy * 5 / 6), quote, anilen, stdscr, 2)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\wisdom_tree\main.py", line 109, in addtext
    stdscr.addstr(
_curses.error: addwstr() returned ERR

**Comment by jav1979** [comment]
Is your terminal sized correctly? ` _curses.error: addwstr() returned ERR` usually means curses is trying to add characters in place outside the terminal.

**Comment by adriantoto** [comment]
Thanks. Yes, that's right, the error is caused by the terminal size. But the other problem (song sometimes is overlap) is not yet detected the cause of the error.
