### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by WhoMI7** [HACKER097/wisdom-tree#40]
`Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Bhatura\AppData\Roaming\Python\Python310\Scripts\wisdom-tree.exe\__main__.py", line 4, in <module>
  File "C:\Users\Bhatura\AppData\Roaming\Python\Python310\site-packages\wisdom_tree\__init__.py", line 1, in <module>
    from .main import *
  File "C:\Users\Bhatura\AppData\Roaming\Python\Python310\site-packages\wisdom_tree\main.py", line 12, in <module>
    import vlc
  File "C:\Users\Bhatura\AppData\Roaming\Python\Python310\site-packages\vlc.py", line 220, in <module>
    dll, plugin_path  = find_lib()
  File "C:\Users\Bhatura\AppData\Roaming\Python\Python310\site-packages\vlc.py", line 180, in find_lib
    dll = ctypes.CDLL('.\\' + libname)
  File "C:\Program Files\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\Bhatura\wisdom-tree\libvlc.dll' (or one of its dependencies). Try using the full path with constructor syntax.`

**Comment by Dandelion75** [comment]
I think It is because VLC installation is not found. Just try to reinstall it in 64 bit because vlc website install it in 32 bit for some reason

**Comment by WhoMI7** [comment]
yup that was it
