### ISSUE TITLE
switching tracks doesn't work

### ISSUE THREAD

**Issue by JoeyMues** [HACKER097/wisdom-tree#7]
Operating system: Windows 10

When I press arrow left/right, or h/l the wisdom tree stops and I get following error:

`Traceback (most recent call last):
  File "C:\Python37\Scripts\wisdom-tree-script.py", line 11, in <module>
    load_entry_point('wisdom-tree==0.0.1', 'console_scripts', 'wisdom-tree')()
  File "c:\python37\lib\site-packages\wisdom_tree\main.py", line 514, in run_app
    main()
  File "c:\python37\lib\site-packages\wisdom_tree\main.py", line 414, in main
    + tree1.music_list[tree1.music_list_num].split("/")[0]
AttributeError: 'WindowsPath' object has no attribute 'split'`

**Comment by HACKER097** [comment]
Issue has now been fixed, please uninstall and install wisdom tree again
